version: '3.5'
services:
  monerod:
    image: sethsimmons/simple-monerod:latest
    restart: unless-stopped
    container_name: monerod
    volumes:
      - bitmonero:/home/monero
    ports:
      - 18080:18080
      - 18089:18089
    command:
      - "--rpc-restricted-bind-ip=0.0.0.0"
      - "--rpc-restricted-bind-port=18089"
      - "--public-node"
      - "--no-igd"
      - "--enable-dns-blocklist"
      - "--prune-blockchain"
  
  monero-wallet-rpc:
    image: sethsimmons/simple-monero-wallet-rpc:latest
    restart: unless-stopped
    container_name: monero-wallet-rpc
    volumes:
      - monero-wallet-rpc-data:/home/monero
    ports:
      - 127.0.0.1:18083:18083
    command:
      - "--daemon-address=monerod:18089"
      - "--trusted-daemon"

  tor:
    image: goldy/tor-hidden-service:latest
    container_name: tor
    restart: unless-stopped
    links:
        - monerod
    environment:
        SERVICE1_TOR_SERVICE_HOSTS: 18089:monerod:18089
        SERVICE1_TOR_SERVICE_VERSION: '3'
    volumes:
        - tor-keys:/var/lib/tor/hidden_service/

autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    restart: unless-stopped
    environment:
        AUTOHEAL_CONTAINER_LABEL: all
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"

watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
    bitmonero:
    tor-keys: